@startuml
left to right direction



rectangle "Car Rental System" {
  actor Customer
  actor Admin

  usecase "Log in" as UC2
  usecase "Sign Up" as UC1
  usecase "Rent a Car" as UC3
  usecase "Return a Car" as UC4
  usecase "View Rentals" as UC5
  usecase "Add Car" as UC6
  usecase "Update Car Info" as UC7
  usecase "Remove Car" as UC8
  usecase "View Car Inventory" as UC9
  usecase "Approve Rental" as UC10
  usecase "Cancel Rental" as UC11
  usecase "Complete Rental" as UC12

  UC2 --> Customer
  UC2 --> Admin
  Customer --> UC3
  Customer --> UC4
  Customer --> UC5

  Admin --> UC6
  Admin --> UC7
  Admin --> UC8
  Admin --> UC9
  Admin --> UC10
  Admin --> UC11
  Admin --> UC12
}
@enduml
